server:
  port: ${PROCESSING_SERVICE_PORT}

user-service:
  get-users-uri: http://${USER_SERVICE_HOST}:${USER_SERVICE_PORT}/users/

spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
      properties:
        spring:
          json:
            add:
              type:
                headers: false
    consumer:
      bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}

topic:
  email: ${EMAIL_TOPIC}
  telegram: ${TELEGRAM_TOPIC}
  sms: ${SMS_TOPIC}