name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build --no-daemon
          EXIT_CODE=$?
          if [[ $EXIT_CODE -ne 0 ]]; then
            echo "Build failed. Aborting the push."
            exit $EXIT_CODE
          fi

      - name: Run Tests
        run: |
          ./gradlew test --no-daemon
          EXIT_CODE=$?
          if [[ $EXIT_CODE -ne 0 ]]; then
            echo "Tests failed. Aborting the push."
            exit $EXIT_CODE
          fi